name: Vineel Sai
bio: Life doesn’t happen to you, it happens for you. 💯
description: A blog about technology and related stuff
external-image: false
picture: assets/images/vineel.png
resume: true
resume-external: true
resume-url: 'https://vineelsai5439.github.io/resume'
url: 'https://vineelsai5439.github.io'
permalink: '/:title/'
disqus:
  shortname: vineel
  categories:
    - blog
    - project
facebook: vineelsai5439
twitter: vineelsai5439
github: vineelsai5439
medium: vineelsai5439
instagram: vineel_sai_73
email: vineelsai5439@gmail.com
authors:
  vineelsai:
    name: Vineel Sai
    bio: Life doesn’t happen to you, it happens for you. 💯
    external-image: false
    picture: assets/images/vineel.jpg
    twitter: vineelsai5439
width: large
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
