title: Vineel Sai
author: Vineel Sai
email: vineelsai5439@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
 Hi, This is my Website
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Vineel Sai
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: VineelSai5
    github:  vineelsai5439
    linkedIn: in/vineel-sai-18a406192
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed