name: Vineel Sai
bio: Life doesn’t happen to you, it happens for you. 💯
description: A blog about technology and stuff related
external-image: false
picture: assets/images/vineel.png
#resume: true
#resume-external: true
#resume-url: 'https://anubhavp28.github.io/Resume/resume.pdf'
url: 'https://vineelsai5439.github.io'
permalink: '/:title/'
disqus:
  shortname: vineel
  categories:
    - blog
    - project
facebook: vineel.sai.vs
twitter: VineelSai5
github: vineelsai5439
#medium: 
email: vineelsai5439@gmail.com
authors:
  vineelsai:
    name: Vineel Sai
    bio: Life doesn’t happen to you, it happens for you. 💯
    external-image: false
    picture: assets/images/vineel.jpg
    twitter: VineelSai5
width: large
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
